### ISSUE TITLE
Possible Out of Bounds error on Remove Inventory At Method

### ISSUE THREAD

**Issue by xLostPro** [MaximasPrime/Inventory-Component#1]
**Describe the bug**
When trying to remove the only item in the inventory using this method I get a out of bounds error. This is due to the output node trying to receive information about an item which doesn't exist in the inventory anymore. Have it fixed in my project but thought I would let you know about it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have only one item in Inventory.
2. Remove said Item from inventory using Remove Inventory At
3. ??????
4. Profit

**Comment by MaximasPrime** [comment]
Thank you, I need to update this.

**Comment by MaximasPrime** [comment]
It is fixed
